USE VIRTUAL_PT;
INSERT INTO PERSON (ID_PERSON, FIRST_NAME, LAST_NAME) VALUES (1, 'Gonçalo', 'Mosqueira');
INSERT INTO PERSON (ID_PERSON, FIRST_NAME, LAST_NAME) VALUES (2, 'Tatiana', 'Costa');
INSERT INTO PERSONAL_TRAINER (ID_PERSON) VALUES (1);
INSERT INTO PERSONAL_TRAINER (ID_PERSON) VALUES (2);
INSERT INTO PERSON (ID_PERSON, FIRST_NAME, LAST_NAME) VALUES (3, 'Fat', 'Joe');
INSERT INTO PERSON (ID_PERSON, FIRST_NAME, LAST_NAME) VALUES (4, 'Monica', 'Bitch');
INSERT INTO PERSON (ID_PERSON, FIRST_NAME, LAST_NAME) VALUES (5, 'Ronald', 'Mcdonalds');
INSERT INTO CLIENT (ID_PERSON) VALUES (3);
INSERT INTO CLIENT (ID_PERSON) VALUES (4);
INSERT INTO CLIENT (ID_PERSON) VALUES (5);
INSERT INTO PERSONAL_TRAINER_CLIENT (REFID_PERSONAL_TRAINER, REFID_CLIENT) VALUES (1, 3);
INSERT INTO PERSONAL_TRAINER_CLIENT (REFID_PERSONAL_TRAINER, REFID_CLIENT) VALUES (1, 4);
INSERT INTO PERSONAL_TRAINER_CLIENT (REFID_PERSONAL_TRAINER, REFID_CLIENT) VALUES (1, 5);


