SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS VIRTUAL_PT;
CREATE SCHEMA IF NOT EXISTS VIRTUAL_PT
  DEFAULT CHARACTER SET latin1;
USE VIRTUAL_PT;

CREATE TABLE USER (
  ID_USER  BIGINT(10)  NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_USER)
)
  ENGINE = InnoDB;

CREATE TABLE PERSON (
  ID_PERSON  BIGINT(10)  NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME  VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_PERSON)
)
  ENGINE = InnoDB;

CREATE TABLE USER_PERSON (
  REFID_USER   BIGINT(10) NOT NULL,
  REFID_PERSON BIGINT(10) NOT NULL,
  PRIMARY KEY (REFID_USER, REFID_PERSON),
  CONSTRAINT FK_USER_PERSON_1 FOREIGN KEY (REFID_USER) REFERENCES USER (ID_USER),
  CONSTRAINT FK_USER_PERSON_2 FOREIGN KEY (REFID_PERSON) REFERENCES PERSON (ID_PERSON)
)
  ENGINE = InnoDB;

CREATE TABLE CLIENT (
  ID_PERSON BIGINT(10) NOT NULL,
  PRIMARY KEY (ID_PERSON),
  CONSTRAINT FK_CLIENT_1 FOREIGN KEY (ID_PERSON) REFERENCES PERSON (ID_PERSON)
)
  ENGINE = InnoDB;

CREATE TABLE PERSONAL_TRAINER (
  ID_PERSON BIGINT(10) NOT NULL,
  PRIMARY KEY (ID_PERSON),
  CONSTRAINT FK_PERSONAL_TRAINER_1 FOREIGN KEY (ID_PERSON) REFERENCES PERSON (ID_PERSON)
)
  ENGINE = InnoDB;

CREATE TABLE PT_CLIENT_ASSOCIATION (
  ID_PT_CLIENT_ASSOCIATION BIGINT(10) NOT NULL AUTO_INCREMENT,
  REFID_PERSONAL_TRAINER   BIGINT(10) NOT NULL,
  REFID_CLIENT             BIGINT(10),
  PRIMARY KEY (ID_PT_CLIENT_ASSOCIATION),
  CONSTRAINT FK_PT_CLIENT_ASSOCIATION_1 FOREIGN KEY (REFID_PERSONAL_TRAINER) REFERENCES PERSONAL_TRAINER (ID_PERSON),
  CONSTRAINT FK_PT_CLIENT_ASSOCIATION_2 FOREIGN KEY (REFID_CLIENT) REFERENCES CLIENT (ID_PERSON)
)
  ENGINE = InnoDB;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;